### ISSUE TITLE
Miniflux version 2.14 & n8n 

### ISSUE THREAD

**Issue by askans** [that-one-tom/n8n-nodes-miniflux#1]
Thank you very much for your Miniflux n8n community node!

Until recently the node was working for me. I had installed Miniflux on my VPS with Caprover. I don't remember the version

Now I have Miniflux 2.14 installed via Yunohost on my VPS. Now your great node does no seem to work, as I cannot fetch the categories (under Options) successfully anymore. Any idea what yould be wrong (on my side)?

**Comment by that-one-tom** [comment]
Thanks for your kind words @askans!

Probably nothing wrong on your end tbh, I just haven't looked at this node or Miniflux for a while, it might just be some API change. Could you try running the node's standalone Category > Get All operation and let me know what error you get (if any)?

It should look like so:

![Screenshot 2024-08-02 at 14-28-08 n8n - ▶️ My workflow 2](https://github.com/user-attachments/assets/4a39438d-fc0f-4352-87a3-8a521b9c5dc7)
