### ISSUE TITLE
[Adding feature] Add Fetch original article API endpoints into n8n nodes miniflux

### ISSUE THREAD

**Issue by NeZios** [that-one-tom/n8n-nodes-miniflux#2]
Hi, 

First, I would like to thank your work for this n8n node that is working very well. 
I would like to suggest adding the feature to _Fetch original article_ https://miniflux.app/docs/api.html#endpoint-fetch-content so we can have the full article in the API, and not the first lines of it. 

Here is an example with an article from The Register : 
<img width="738" alt="image" src="https://github.com/user-attachments/assets/0ddba57f-f373-4ca4-bebc-40ff58e0fe31">

Here is the content inside n8n miniflux node: 
<img width="1450" alt="image" src="https://github.com/user-attachments/assets/37ec661a-ce90-4e5b-9830-be319d2c2c0b">
We can see that the content output shows only the beginning of the article.

Here is the content using the Fetch original article in the API : 
<img width="1087" alt="Capture d’écran 2024-11-12 à 20 09 51" src="https://github.com/user-attachments/assets/483a84c7-6a4f-450a-9f79-6523170a112d">

By using fetch original article we can get the full content of the article using the API. 
This feature combined with your work with Plain Text option can be a great way to gather full articles in n8n.

Thanks,

**Comment by that-one-tom** [comment]
Sounds like a great idea @NeZios, thanks for the suggestion! I'll have some free time next week and give it a try.

**Comment by NeZios** [comment]
Thank you very much, keep us in touch! 🙂

**Comment by that-one-tom** [comment]
This has been added with https://github.com/that-one-tom/n8n-nodes-miniflux/commit/b71f9bcfe27c2850d6ad0d771aca1c488410b905 and the latest node version is now available through NPM as well: https://www.npmjs.com/package/n8n-nodes-miniflux

![image](https://github.com/user-attachments/assets/2e3048a2-c8c7-4204-9a0a-31dc580aa614)

One thing worth noting is that I couldn't get the community node update functionality in n8n to work. So I had to uninstall the previous node version through n8n's Community nodes page, then install the new version. I also had to re-start my n8n instance for the new option to show up.

**Comment by NeZios** [comment]
Thank you very much! I am gonna try that this weekend ! 👍

**Comment by NeZios** [comment]
Hi @that-one-tom 
So, the update works great. 
However I am getting the error : _The service was not able to process your request [item 3]
fetcher: access forbidden (403 status code)_ every time my limit is superior or equal to 3 items. 
Can you confirm me that is normal ? I would like to get 5 items. 
Thanks!
